#!/bin/bash

# background="/home/kevin/GoogleDrive/Background\ Images/lord-of-the-ring-rings-maps-middle-earth-x-3184659.jpg"

# Load resources

xrdb -merge .Xresources

# Set up an icon tray
stalonetray &

# Fire up apps

xscreensaver -no-splash &

# Set background image with feh
if [ -f $BACKGROUND ] ; then
    feh --bg-scale $BACKGROUND &
fi

# Start udiskie to handle media
udiskie &

if [ -x /usr/bin/nm-applet ] ; then
   nm-applet --sm-disable &
fi

ssh-agent xmonad

